weights: yolov5m.pt
cfg: ''
data: D:\projects\yolov5\yolov5\data\custom_avto_nomer2.yaml
hyp: D:\projects\yolov5\yolov5\data\hyps\hyp.avto.med.yaml
epochs: 1000
batch_size: -1
imgsz: 960
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: '''ram'''
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 0
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp3
